{% set version = "1.4.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-kknn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/kknn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/kknn/kknn_{{ version }}.tar.gz
  sha256: 5232ddc268c0f9d691b613c8767a9ce079dade75ee22051a3b928024ada46f34

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-igraph                   # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-matrix
    - r-igraph >=1.0
  run:
    - r-base
    - r-matrix
    - r-igraph >=1.0

test:
  commands:
    - $R -e "library('kknn')"           # [not win]
    - "\"%R%\" -e \"library('kknn')\""  # [win]

about:
  home: https://github.com/KlausVigo/kknn
  license: GPL-2.0-or-later
  summary: Weighted k-Nearest Neighbors for Classification, Regression and Clustering.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
