appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fiiQW4Ib/gPL8Pkz6CeuKvPiGHnY+zo3yCvEWuEdL15eMEF0Uunx2hT6ocqe/SGHRqeTNpEiUJu/0P4bZgZV53jxvoMg329yVUUyitMManwqX9mEaWBNEgMCaacnvbm3qjtghGxjIDeS3OGLQlGiR0B5fbIxqnGo/rii/ExbX7MMek2US/OXgmYdO09QxSAbpwlRI1mDZ3oKEW8ESIWmZM7z3Sk6CBX84DEJ4m8gm+Z9tLG3HY/AxWY53Z3uUlzO7jw9vaSiqDtkXZxcV0EThwoeKQstxvIqblsopfjl1pQdn6jJsSPx0DcwoanRd6Yw18NpmA2qx3NMlYLIyz//8XSASxhjo3iEkWNWqoYLjBkoQOQMF7lh7BsiqrvM8wUkyLXZT1GsjM1SPM3cU8W8Crx9rfnJ88MqtQUSQlw4CPRG/8VU2vju1VBS2mF9BauXliFXUDFKOFujB6z4beXnEDEdiRQ/0JoHPS/A9pBK10jgsC/PUcIXLX4Tnj1QgAXKhdQtOcg0P3CYB1BCyGs8xSQ/EDep41/SJ6XlTMTFEAsYIrV6vJK2uGc0w83ydxKQijf9KhLv1Lx0gjiIN7tttM2WU07ftPJbBJPOoUivs8U5PF/YgFBB9a1TJY1o7UoOhA8U/Up45rxbzmVviSrvKCpUxzEECPdM7rTOgnDR1EM=}
